// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH5eGSf1YZPbyahV91WJawy5ifTf7ybbk',
    appId: '1:121121792337:web:35bd50ebef7cf54f1bf370',
    messagingSenderId: '121121792337',
    projectId: 'note-app-cb433',
    authDomain: 'note-app-cb433.firebaseapp.com',
    storageBucket: 'note-app-cb433.appspot.com',
    measurementId: 'G-RXN9C9M9K0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjUYYemDp1-rCjzO0KW6oZUh8Mu-E0WW4',
    appId: '1:121121792337:android:be67a1d72d1dc63a1bf370',
    messagingSenderId: '121121792337',
    projectId: 'note-app-cb433',
    storageBucket: 'note-app-cb433.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXAePM3CSI2aIUm6qCShWicCdnfS94fXM',
    appId: '1:121121792337:ios:21013232cd2919d01bf370',
    messagingSenderId: '121121792337',
    projectId: 'note-app-cb433',
    storageBucket: 'note-app-cb433.appspot.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXAePM3CSI2aIUm6qCShWicCdnfS94fXM',
    appId: '1:121121792337:ios:31d9c24f78af19ab1bf370',
    messagingSenderId: '121121792337',
    projectId: 'note-app-cb433',
    storageBucket: 'note-app-cb433.appspot.com',
    iosBundleId: 'com.example.noteApp.RunnerTests',
  );
}
